### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### geoCML/kasm-gis-workspace now has a Chat Room on Gitter

@TristanDamron has just created a chat room. You can visit it here: [https://gitter.im/geoCML/geoCML-development](https://gitter.im/geoCML/geoCML-development?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/geoCML/geoCML-development?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://gitlab.com/gitlab-org/gitter/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by TristanDamron** [comment]
@capsulecorplab I thought that it might be a good idea for this project to have an Gitter chatroom to promote community engagement. Let me know what you think of this!

**Comment by TristanDamron** [comment]
Whoops! Realized that the Gitter badge didn't redirect to the main community page. That's fixed now with f528055!

**Comment by capsulecorplab** [comment]
I haven't had a pleasant experience with Gitter, tbh. Discussion threads get lost and/or become difficult to follow when you have multiple discussions happening simultaneously. I think a better alternative to consider would be [GitHub Discussions](https://docs.github.com/en/discussions)

**Comment by TristanDamron** [comment]
Sounds good to me! We'll use Github Discussions instead :smile:

**Pull request closed without merging**
